domain: apecseminar.github.io
url: https://apecseminar.github.io/
theme: minima
# remote_theme: something cool from  http://jekyllthemes.org/
title: Applied Economics Seminar
description: Applied Economics Seminar at the University of Minnesota