---
title: "Diveristy, Equity, and Inclusion (DEI)"
comments: false
---

The Applied Economics department is a welcoming and inclusive environment for all members who wish to respectfully participate. 
We recognize the inequities of disadvantaged groups in the research process. 
As such, we strongly encourage and support the active presentation of research by researchers who identify as a member of a disadvantaged or minority group. 

This is a page of resources related to DEI for the Applied Economics program at the University of Minnesota. 
The current DEI student representative is [Giang Thai](https://www.linkedin.com/in/giang-thai-05b18046). 
The current Diversity & Inclusion Committee Chair is [Dr. Hikaru Peterson](https://apec.umn.edu/people/hikaru-peterson). 
Concerns related to DEI at the department level are addressed via the Diversity Equity and Inclusion Committee.
The department's resources and stance on DEI may be found through the [APEC Website](https://apec.umn.edu/dei).
More broadly, the University of Minnesota has an [Office of Equity and Diversity](https://diversity.umn.edu/) with resources and support on DEI-related material.
Graduate students can use the [Graduate Student Resource Guide](https://docs.google.com/document/d/15zb9IlSKAt7K7rg-pC_QvTFvQvC6yvqU7jLLIgr616E/edit) to find UMN based graduate resources to support them.

# DEI Statement

# DEI Resources

- ISRDI DEI Researcher Toolkit

# Advice for Preparing DEI Statements


### DEI-Related Organizations and Programs

| **Organization**   | **Host** |
| :---        |    ---: |
| [Diversity Fellowship Program](https://isrdi.umn.edu/diversity-fellowship-program)        |    ISRDI |
| [Diversity of Views and Experiences (DOVE) Fellows Program](https://grad.umn.edu/diversity/community-scholars-program)        |    UMN |


### DEI-Related  Funding 

| **Funding**   | **Type** | **Host** | 
| :---        |    :----:   |    ---: |
| [AEA Award for Outstanding Achievement in Diversity and Inclusion](https://www.aeaweb.org/about-aea/honors-awards/outstanding-achieve-diversity-inclusion)       |    Award   |    AEA |
| [Departmental Seed Grants for Innovation in Diversity and Inclusion](https://www.aeaweb.org/about-aea/committees/csmgep/diversity-initiatives/dept-seed-grants)       |    Grant  |    AEA |
| [URM Travel Grants](https://www.aeaweb.org/about-aea/committees/csmgep/diversity-initiatives/urm-travel-grants)       |    Grant  |    AEA |

## LGBTQ+ Student Resources


### LGBTQ+ Organizations and Programs

| **Organization**   | **Host** |
| :---        |    ---: |
| [The Committee on the Status of Minority Groups in the Economics Profession (CSMGEP)](https://www.aeaweb.org/about-aea/committees/csmgep)        |    AEA |
| [Diversity Fellowship Program](https://isrdi.umn.edu/diversity-fellowship-program)        |    ISRDI |
| [Empowering Women in Science](https://ewis.umn.edu/)        |    UMN |



### LGBTQ+ Funding 


| **Funding**   | **Type** | **Host** | 
| :---        |    :----:   |    ---: |
| [AEA Award for Outstanding Achievement in Diversity and Inclusion](https://www.aeaweb.org/about-aea/honors-awards/outstanding-achieve-diversity-inclusion)       |    Award   |    AEA |
| [Departmental Seed Grants for Innovation in Diversity and Inclusion](https://www.aeaweb.org/about-aea/committees/csmgep/diversity-initiatives/dept-seed-grants)       |    Grant  |    AEA |
| [URM Travel Grants](https://www.aeaweb.org/about-aea/committees/csmgep/diversity-initiatives/urm-travel-grants)       |    Grant  |    AEA |
| [Award for Outstanding Research Paper in LGBTQ+ Economics]( https://www.aeaweb.org/about-aea/committees/aealgbtq/csqiep-award)       |    Award  |    AEA |
| [The Carolyn Shaw Bell Award](https://www.aeaweb.org/about-aea/committees/cswep/awards/bell)       |    Award  |    AEA |
| [The Elaine Bennett Research Prize](https://www.aeaweb.org/about-aea/committees/cswep/awards/bennett)       |    Award  |    AEA |


