---
title: "Past Seminar & Workshop Series"
comments: false
---

# 2025 Spring Speaker Schedule

<!-- ## Student Seminar Schedule -->

<!-- | **Speaker**      | **Affiliation** | **Date** | **Title** |
| :---        |    :----:   |   :----:   |    :----:   |    ---: |
| [Ling Yao](https://apec.umn.edu/people/ling-yao)     | Applied Economics, UMN   |   Sept. 4th   |  Agricultural Mechanization and Structural Transformation | -->


## Skills Workshop Schedule

| **Speaker**      |  **Date** | **Title** |  **Link to Materials/Slides** |  **Presentation Recording** |
| :---        |    :----:   |    :----:   |    :----:   |    ---: |
| [Raahil Madhok](https://www.raahilmadhok.com/)    |   Jan. 29th |  Using the Bartik Instrumental Variable (Shift-share IV)   | [Slides](/slides/2025_spring/slides_raahil_madhok_250129.pdf)  | [YouTube](https://www.youtube.com/watch?v=sdyd7HN8A0M) | 
| [Paul Glewwe](https://apec.umn.edu/people/paul-glewwe)    |   Mar. 26th |  Fieldwork Management   | [Slides](/slides/2025_spring/slides_paul_glewwe_250326.pdf)  | [YouTube](https://youtu.be/WkXxUJJhqNI) | 
| [Ling Yao](https://apec.umn.edu/people/paul-glewwe)    |   Apr. 2nd |  Teaching as a Graduate Student   | [Slides](/slides/2025_spring/slides_ling_yao_250402.pdf)  | [YouTube]() | 



# 2024 Fall Speaker Schedule

## Student Seminar Schedule

| **Speaker**      | **Affiliation** | **Date** | **Title** | **Link to Poster** |
| :---        |    :----:   |   :----:   |    :----:   |    ---: |
| [Ling Yao](https://apec.umn.edu/people/ling-yao)     | Applied Economics, UMN   |   Sept. 4th   |  Agricultural Mechanization and Structural Transformation | [Poster](/posters/2024_fall/ling_yao_240904.pdf)    |
| [Lindsey Novak](https://www.lindseyknovak.com/)     | Reed College   |   Sept. 18th   |  Overall Research Agenda and Tips for the Job Market | [Poster](/posters/2024_fall/lindsey_novak_240918.pdf)    |
| [Jiuchen Deng](https://sites.google.com/view/jiuchendeng/home)     | Applied Economics, UMN   |   Oct. 2nd  |  The Development of Personality Traits and Cognitive Skills in Adolescence: Evidence from a Skill Formation Model and a Control Function Approach | [Poster](/posters/2024_fall/jiuchen_deng_241002.pdf)    |
| [Evan Cunningham](https://www.evanrcunningham.com/)     | Economics, UMN   |   Oct. 16th  |  Local Labor Market Effects of Amazon | [Poster](/posters/2024_fall/evan_cunningham_241016.pdf)    |
| [Divya Pandey](https://divyapandey.me/)     | Applied Economics, UMN   |   Oct. 30th   |   The Impact of Weather Shocks on Fertility in Rural India | [Poster](/posters/2024_fall/divya_pandey_241030.pdf)    |
| [Monique Davis](https://www.moniqueedavis.com/)     | Applied Economics, UMN   |   Nov. 6th  |   Safety for Whom? How Law Enforcement and School Resource Officer Training Impacts Racial Gaps in School Exclusionary | [Poster](/posters/2024_fall/monique_davis_241106.pdf)    |
| [Qingyin Cai](https://www.qingyincai.com/)     | Applied Economics, UMN   |   Nov. 13th   |  Drought and the Specialty Crop Production in California | [Poster](/posters/2024_fall/qingyin_cai_241113.pdf)    |
| [Yanxu Long](https://yanxulong.github.io/)     | Applied Economics, UMN   |   Nov. 27th  |  Payments for Ecosystem Services, Reforestation and Rural Livelihoods | [Poster](/posters/2024_fall/yanxu_long_241127.pdf)    |
| [Ana Melissa Perez](https://apec.umn.edu/people/ana-melissa-perez-castano)     | Applied Economics, UMN   |   Dec. 11th   |  Mass Shootings and their Effects on Food Shopping Behavior | [Poster](/posters/2024_fall/ana_melissa_perez_241211.pdf)    |


## Skills Workshop Schedule

| **Speaker**      |  **Date** | **Title** | **Link to Poster** |  **Link to Materials/Slides** |  **Presentation Recording** |
| :---        |    :----:   |    :----:   |    :----:   |    :----:   |    ---: |
| [Yufeng Lai](https://www.laiyufeng.com/)    |   Sept. 11th |  Non-traditional skills for Economists to Deliver in the Tech Sector | [Poster](/posters/2024_fall/yufeng_lai_240911.pdf)    | [Slides](/slides/2024_fall/slides_yufeng_lai_240911.pdf)  | [YouTube](https://www.youtube.com/watch?v=pSmrhKCYP84) | 
| [Abel Broduer](https://sites.google.com/site/abelbrodeur/)    |   Sept. 25th  |  Reproducibility, Replication Packets, and Pre-analysis Plans | [Poster](/posters/2024_fall/abel_broduer_240925.pdf)    | [Slides](/slides/2024_fall/slides_abel_broduer_240925.pdf)  | [YouTube](https://youtu.be/Sgc8DDrqKes) | 
| [Willy Lee](https://www.linkedin.com/in/willylee)    |   Oct. 9th  |  Diversity, Equity, and Inclusion (DEI) in Academia and DEI Statements for the Job Market | [Poster](/posters/2024_fall/willy_lee_241009.pdf)    | [Slides](https://docs.google.com/presentation/d/1_h7-TRhrEtxLRRf_VDQdV52Nkq250W0DHdLA49s44es/edit?usp=sharing)  | [YouTube](https://www.youtube.com/watch?v=8FNEwriuRIs) | 
| [Caroline Krafft](https://carolinekrafft.com/)    |   Oct. 23rd  |  Survey Design | [Poster](/posters/2024_fall/caroline_krafft_241023.pdf)    | [Slides](/slides/2024_fall/slides_caroline_krafft_241023.pdf)  | [YouTube](https://youtu.be/Ge_pyl7NkwA) | 
| [David Redish](https://med.umn.edu/bio/david-redish)    |   Nov. 20th  |  Why Economists Need to Know the Neuroscience | [Poster](/posters/2024_fall/david_redish_241120.pdf)    | [Slides](/slides/2024_fall/slides_david_redish_241120.pdf)  | [YouTube]() | 
| [Natalia Ordaz Reynoso](https://www.nataliaordazreynoso.com/)    |   Dec. 4th  |  Working in Tech Sector as an Economist | [Poster](/posters/2024_fall/natalia_ordaz_reynoso_241204.pdf)    | [Slides](/slides/2024_fall/slides_natalia_ordaz_reynoso_241204.pdf)  | [YouTube](https://youtu.be/IHN1dR6QlP0) | 



# 2024 Spring Speaker Schedule

## Student Seminar Schedule

| **Speaker**      | **Affiliation** | **Date** | **Title** | **Link to Poster** |
| :---        |    :----:   |   :----:   |    :----:   |    ---: |
| [Corissa Marson](https://apec.umn.edu/people/corissa-marson)     | Applied Economics, UMN   |   Jan. 17th   |  How Does Information Avoidance Determine the Effect of Information on Consumer Willingness to Pay: A Case Study on Genetically Modified and Gene Edited Crops | [Poster](/posters/2024_spring/corissa_marson_240117.pdf)    |
| [Haku Bo](https://www.linkedin.com/in/hakuub)     | Applied Economics, UMN   |   Jan. 31st   |  Net Incomes of Pastoralism and Its Influencers | [Poster](/posters/2024_spring/haku_bo_240131.pdf)    |
| [SongYi Paik](https://www.songyipaik.com/)     | Applied Economics, UMN   |   Feb. 14th   |  Slow Violence of Waste: Evidence from Chinese Environmental Policy in Waste Trade | [Poster](/posters/2024_spring/songyi_paik_240214.pdf)    |
| [Monique Davis](https://www.moniqueedavis.com/)     | Applied Economics, UMN   |   Feb. 28th   |  School Resource Officer Selection and Training on Racial Disparities in Exclusion | [Poster](/posters/2024_spring/monique_davis_240228.pdf)    |
| [Kadidiatou (Kadidja) Doucouré](https://kadidjadoucoure.weebly.com/)     | Loyola University Maryland   |   Mar. 13th   |  Exchange Rate Regimes and Firms Performance: Evidence from West African Countries | [Poster](/posters/2024_spring/kadidja_doucoure_240313.pdf)    |
| [Haishan Yang](https://au.linkedin.com/in/haishan-yang-a08b5412a)     | Public Health, UMN   |   Mar. 26th   |  Disaster and Disparity: The Heterogenous Effect of Hurricane Katrina on Rental Market | [Poster](/posters/2024_spring/haishan_yang_240326.pdf)    |
| [Natalia Pia Guerrero Trinidad](https://apec.umn.edu/people/natalia-guerrero-trinidad)     | Applied Economics, UMN   |   Apr. 9th   |  The Role of Bonding and Bridging Social Capital by Non-State Social Structures: Evidence on Crime and Conflict in Peru | [Poster](/posters/2024_spring/natalia_pia_guerrero_trinidad_240409.pdf)    |
| [Yu Na Lee](https://sites.google.com/view/yu-na-lee/home)     | University of Guelph   |   Apr. 23rd   |  Food Price and Child Marriage | [Poster](/posters/2024_spring/yu_na_lee_240423.pdf)    | 

## Skills Workshop Schedule


| **Speaker**      |  **Date** | **Title** | **Link to Poster** |  **Link to Materials/Slides** |  **Presentation Recording** |
| :---        |    :----:   |    :----:   |    :----:   |    :----:   |    ---: |
| [Matt Bombyk](https://www.linkedin.com/in/matthew-bombyk-33b09642)    |   Jan. 24th   |  Software to Improve Research Efficiency: Onenote, Anki, estout | [Poster](/posters/2024_spring/matt_bombyk_240124.pdf)    | [Estout Script](/slides/2024_spring/script_matt_bombyk_240124.do) [& Output](/slides/2024_spring/output_matt_bombyk_240124.pdf) | [YouTube](https://www.youtube.com/watch?v=BwbPJhKc0x0) | 
| [Khoa Vu](https://sites.google.com/view/khoavu-umn/home)    |   Feb. 7th   |  Preparing for the Industry Job Market | [Poster](/posters/2024_spring/khoa_vu_240207.pdf)    | [Slides](/slides/2024_spring/slides_khoa_vu_240207.pdf) | [YouTube](https://www.youtube.com/watch?v=HqclX8GJzpw) | 
| [Jay Coggins](https://apec.umn.edu/people/jay-coggins)    |   Feb. 21st   |  Creating Theory in Practice: An Application from Environmental/Welfare Economics | [Poster](/posters/2024_spring/jay_coggins_240221.pdf)    | [Slides](/slides/2024_spring/slides_jay_coggins_240221.pdf) | [YouTube](https://www.youtube.com/watch?v=-4Umg5mrVeQ) | 
| [Thomas Durfee](https://sites.google.com/view/thomas-durfee/home)    |   Mar. 19th   |  The UMN Supercomputer and Large Dataset Best Practices | [Poster](/posters/2024_spring/thomas_durfee_240319.pdf)    | No Slides  | [YouTube Part 1](https://youtu.be/Uw6_cEdRh-I) [YouTube Part 2](https://youtu.be/mXPmBBrWPMQ) | 
| [Metin Cakir](https://apec.umn.edu/people/metin-cakir)    |   Apr. 2nd   |  Tips for Writing Competitive Grants | [Poster](/posters/2024_spring/metin_cakir_240402.pdf)    | [Slides](/slides/2024_spring/slides_metin_cakir_240402.pdf) | [YouTube](https://youtu.be/M5WoN9-n6vo) | 
| Jhih-Yun Liu, Thomas Durfee, Rebecca Weir   |   Apr. 16th   |  Reflections and Advice about the Job Market | [Poster](/posters/2024_spring/job_market_240416.pdf)    | No Slides | No Recording | 
| [Shunkei Kakimoto](https://apec.umn.edu/people/shunkei-kakimoto)    |   Apr. 30th   |  Introduction to Making Presentation Slides with Xaringan | [Poster](/posters/2024_spring/shunkei_kakimoto_240430.pdf)    | [Github Repo](https://github.com/Shunkei3/APEC_xaringanPresentations) | [YouTube](https://youtu.be/4vFSbJG34uk) |


# 2023 Fall Speaker Schedule

## Student Seminar Schedule

| **Speaker**      | **Affiliation** | **Date** | **Title** | **Link to Poster** |
| :---        |    :----:   |   :----:   |    :----:   |    ---: |
| [Rodrigo Franco](https://www.rodrigofrancor.com/)     | Applied Economics, UMN   |   Sept. 6th   |  Estimating Treatment Effects, with Less Conservative Standard Errors An Empirical Approach to Borusyak, Jararvel, and Spiess (2021) | [Poster](/posters/2023_fall/rodrigo_franco_230906.pdf)    |
| [Matt Bombyk](https://www.linkedin.com/in/matthew-bombyk-33b09642)  | Applied Economics, UMN    | Sept. 20th       |   Minimum Wage Inflation Indexing and Employment   | [Poster](/posters/2023_fall/matt_bombyk_230920.pdf)  |
| [Hosam Ibrahim](https://www.linkedin.com/in/hosam-ibrahim-b834522b)  | Applied Economics, UMN    | Oct. 4th      |   Matching prior DiD and sampling: Designing the evaluation for the Morocco Pioneer School Program  | [Poster](/posters/2023_fall/hosam_ibrahim_231004.pdf)    |
| [Aiden Opatz](https://apec.umn.edu/people/aiden-opatz)  | Applied Economics, UMN    | Oct. 18th      |   Hurricanes and Human Migration   | [Poster](/posters/2023_fall/aiden_opatz_231018.pdf)    |
| [Jeff Bloem](https://jeffbloem.wordpress.com/)  | IFPRI    | Nov. 1st     |   Myths and Facts about Agri-Food Value Chains: A Respondent-Driven Sampling Approach   | [Poster](/posters/2023_fall/jeff_bloem_231101.pdf)    |
| [Wahed Rahman](https://www.kwrahman.com/)  | Oxford University    | Nov. 15th      |   The Mode of Testing and Learning Outcomes: Evidence from In-person and Phone tests   | [Poster](/posters/2023_fall/wahed_rahman_231115.pdf)    |
| [Stephen Pitts](https://spittssj.github.io/)  | Applied Economics, UMN    | Nov. 29th      |   Sweet and Timely Insurance: The Role of Honey in Reducing Coffee Producer Food Insecurity Exposure in Mexico   | [Poster](/posters/2023_fall/stephen_pitts_231129.pdf)    |
| [Caitlyn Keo](https://www.linkedin.com/in/caitlyn-keo)  | Applied Economics, UMN    | Dec. 13th      |   Reforming Child Protection Services: The Effect of Differential Response on Subsequent Maltreatment for Reported Children | [Poster](/posters/2023_fall/caitlyn_keo_231213.pdf)    |


## Skills Workshop Schedule

| **Speaker**      |  **Date** | **Title** | **Link to Poster** |  **Link to Materials/Slides** |  **Presentation Recording** |
| :---        |    :----:   |    :----:   |    :----:   |    :----:   |    ---: |
| [Lifeng Ren](https://www.lifengren.com)     |    Sept. 13th   |  Working with Quarto Notebooks | [Poster](/posters/2023_fall/lifeng_ren_230913.pdf)    | [Github Repository](https://www.lifengren.com/quarto_notebook.html) | [YouTube](https://www.youtube.com/watch?v=GslyujSnkZ4) |
| [Libby Kula](https://www.linkedin.com/in/elizabeth-kula)    |   Sept. 27th   |  Intro to Zotero and Efficient Literature Review Practices | [Poster](/posters/2023_fall/libby_kula_230927.pdf)    | [Slides](/slides/2023_fall/slides_libby_kula_230927.pdf) | [YouTube](https://www.youtube.com/watch?v=Qt1ES4lEDQk) |
| [Terry Hurley](https://apec.umn.edu/people/terrance-hurley)   |   Oct. 11th   |  Insights from the Theory of the Firm into Structural and Reduce Form Equation Modeling | [Poster](/posters/2023_fall/terry_hurley_231011.pdf)    |  [Slides](/slides/2023_fall/slides_terry_hurley_231011.pdf) | [YouTube](https://www.youtube.com/watch?v=N6HVmphdKVA) |
| [Charlotte Ambrozek](https://charlotteambrozek.weebly.com/)    |   Oct. 25th   |  Networking for the Job Market and Beyond | [Poster](/posters/2023_fall/charlotte_ambrozek_231025.pdf)    |  No Slides | [YouTube](https://youtu.be/ESJ3R4KtrQA) |
| [Haseeb Ali](https://www.linkedin.com/in/haseeb-ali-8128b652)    |   Nov. 8th   |  Using Git and Github for Version Control and Project Collaboration | [Poster](/posters/2023_fall/haseeb_ali_231108.pdf)    |  [Slides](/slides/2023_fall/slides_haseeb_ali_231108.pdf) | [YouTube](https://youtu.be/zvn2rYQKcmo) |
| [Matt Bombyk](https://www.linkedin.com/in/matthew-bombyk-33b09642)   |   Dec. 6th   |  Advancements in the Difference in Differences Literature | [Poster](/posters/2023_fall/matt_bombyk_231206.pdf)    |  [Slides](/slides/2023_fall/slides_matt_bombyk_231206.pdf) | [YouTube](https://youtu.be/YzVJc7EC9ok) |

# 2023 Spring Speaker Schedule

## Student Seminar Schedule

| **Speaker**      | **Affiliation** | **Date** | **Title** | 
| :---        |    :----:   |    :----:   |    ---: |
| [Colette Salemi](https://colettesalemi.com/)      | University of Victoria   |   Feb. 9th   |  Does Perceived Labor Market Competition Increase Prejudice between Refugees and their Hosts? Evidence from Uganda and Ethiopia.   |
| [Chris Boyd](https://www.chrismboyd.com/)   | Towson University    |    Mar. 23rd     |   Recent Research and Tips for the Job Market   |
| [Ryan McWay](https://mcwayrm.github.io/)   | Applied Economics, UMN    |    Apr. 13th    |   Locust Swarms and Economic Damages   |
| [Qingxiao Li](https://www.lsu.edu/agriculture/agecon/people/bio/qingxiao-li.php)  | Lousiana State University    |    Apr. 20th    |   Recent Research and Tips for the Job Market   |
| [Carmen Armas Montalvo](https://pe.linkedin.com/in/carmen-armas-montalvo/en)  | Applied Economics, UMN    |    May 4th    |   Does the NiUnaMenos Movement Help Increase Female Bargaining Power? Evidence from a Peruvian Public Policy   |

# 2022 Fall Speaker Schedule

## Student Seminar Schedule

| **Speaker**      | **Affiliation** | **Date** | **Title** | 
| :---        |    :----:   |   :----:   |    ---: |
| [Stephen Pitts](https://apec.umn.edu/people/stephen-pitts)      | Applied Economics, UMN   |   Oct. 14th    |  Lessons Learned from Field Research Funded by CIFAP  |
| [Monique Davis](https://www.moniqueedavis.com/)  | Applied Economics, UMN    | Oct. 28th       |   Law Enforcement Officers in Schools   |
| [Jhih-Yun Liu](https://www.jhihyunliu.com/)  | Applied Economics, UMN    | Nov. 11th       |   Occupational Persistence in Agriculture   |